#!/bin/bash

cp /usr/share/zoneinfo/Pacific/Auckland /etc/localtime

# copy maori keyboard layout
cp /media/mi /usr/share/X11/xkb/symbols
# select the maori keyboard
sed -i -e 's/us/mi/' /etc/sysconfig/keyboard
# update olpc configure to select maori instead of what is in the manufacturing data
mkdir -p /etc/olpc-configure
echo mi >/etc/olpc-configure/default-kbd-layout

# update Maori translations
sh /media/mi_lang_pack_v2.sh
