#!/bin/bash

cp /usr/share/zoneinfo/Pacific/Auckland /etc/localtime

# copy maori keyboard layout
cp /media/mi /usr/share/X11/xkb/symbols
# select the maori keyboard
sed -i -e 's/us/mi/' /etc/sysconfig/keyboard
# hack olpc configure to select maori instead of what is in the manufacturing data
sed -i -e 's/XKBLAYOUT="$XKBLAYOUT"/XKBLAYOUT="mi"/' /usr/sbin/olpc-configure
